import SwiftUI
import CoreData

struct EditTaskView: View {
    @Environment(\.managedObjectContext) private var ctx

    // TaskEntry is an NSManagedObject generated by Core Data
    @ObservedObject var task: TaskEntry

    var body: some View {
        Form {
            // MARK: Task Details
            Section(header: Text("Task Details")) {
                TextField("Title", text: Binding(
                    get: { task.title ?? "" },
                    set: { task.title = $0 }
                ))
                Toggle("Completed", isOn: $task.isCompleted)
            }

            // MARK: Due Date
            Section {
                DatePicker(
                    "Due Date",
                    selection: Binding(
                        get: { task.dueDate ?? Date() },
                        set: { task.dueDate = $0 }
                    ),
                    displayedComponents: .date
                )
            }
        }
        .navigationTitle("Edit Task")
        // Persist edits automatically when leaving the screen
        .onDisappear {
            try? ctx.save()
        }
    }
}
